version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Instalando dependencias..."
      - pip install --upgrade pip
      - pip install -r requirements.txt
      
  build:
    commands:
      - echo "Ejecutando Streamlit..."
      - nohup streamlit run CronoPU.py --server.port 8501 --server.enableCORS false --server.enableXsrfProtection false &

artifacts:
  files:
    - '**/*'


