version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Instalar las dependencias necesarias, incluyendo Streamlit y cualquier otra librería
      echo "Instalando dependencias..."
      pip install -r requirements.txt
  build:
    commands:
      # Ejecutar Streamlit (usando 'streamlit run' para iniciar la aplicación)
      echo "Ejecutando Streamlit..."
      streamlit run CronoPU.py
artifacts:
  files:
    - '**/*'

